/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Rectangle;
import java.awt.TexturePaint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;

/**
 *
 * @author Soroush
 */
public class GraphicPanel extends javax.swing.JPanel implements ActionListener {

    private JButton b;
    private JLabel lr;
    private JLabel lg;
    private JLabel lb;
    
    /**
     * Creates new form GraphicPanel
     */
    public GraphicPanel() {
        initComponents();
        setBackground(Color.white);
        setLayout(new FlowLayout());
        b = new JButton("Choose Color");
        b.addActionListener(this);
        add(b);
        lr = new JLabel("R");
        lg = new JLabel("G");
        lb = new JLabel("B");
        add(lr);
        add(lg);
        add(lb);
    }
    
    @Override
    public void paintComponent(Graphics g1) {
        
        super.paintComponent(g1);
        
        Graphics2D g = (Graphics2D)g1;
        
        Random r = new Random();
        /*
        g.setPaint(Color.red);
        g.drawRect(12, 25, 100, 20);
        g.setColor(new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256)));
        g.fillRect(12, 50, 100, 20);
        g.drawString("Hello World!", 12, 100);
        g.setColor(Color.black);
        g.drawRoundRect(12, 120, 50, 50, 10, 10);
        g.fillRoundRect(12, 200, 50, 50, 30, 30);
        g.drawOval(100, 10, 40, 60);
        g.drawLine(100, 70, 150, 100);
        g.drawArc(100, 150, 50, 50, 370, -270);
        g.fillArc(100, 220, 50, 50, 370, -270);
        
        Polygon p = new Polygon();
        
        for (int i = 0; i < 50; i++) {
            p.addPoint(200 + r.nextInt(100), 100 + r.nextInt(100));
        }
        
        g.drawPolygon(p);
        
        g.setPaint(new GradientPaint(300, 300, Color.yellow, 310, 330, Color.blue, true));
        g.fillRect(300, 300, 100, 300);
        //g.fillOval(600, 300, 200, 200);
        //g.fill(new Rectangle2D.Double(600, 600, 100, 100));
        //g.fill(new Ellipse2D.Double(800, 300, 100, 200));
        
        g.setStroke(new BasicStroke(15));
        */
        BufferedImage img = new BufferedImage(10, 10, BufferedImage.TYPE_INT_RGB);
        try {
            img = (BufferedImage)ImageIO.read(getClass().getResource("a.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(GraphicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        g.setPaint(new TexturePaint(img, new Rectangle(20, 20)));
        g.fill(new Rectangle2D.Double(400, 300, img.getWidth(), img.getHeight()));
        
        g.draw(new Rectangle2D.Double(800, 300, 100, 200));
        */
        
        Person p = new Person(200, 200, 40, new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256)), new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256)));
        //p.draw(g);
        
        for (int i = 1; i < 6; i++) {
            //g.rotate(Math.PI / 3);
            p.setX(p.getX() + 200);
            p.draw(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Color c = Color.yellow;
        c = JColorChooser.showDialog(this, ":)", c);
        if (c != null) {
            b.setBackground(c);
            lr.setOpaque(true);
            lg.setOpaque(true);
            lb.setOpaque(true);
            lr.setBackground(new Color(c.getRed(), c.getRed(), c.getRed()));
            lg.setBackground(new Color(c.getGreen(), c.getGreen(), c.getGreen()));
            lb.setBackground(new Color(c.getBlue(), c.getBlue(), c.getBlue()));
        }
    }
}
