/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Polygon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;

/**
 *
 * @author Soroush
 */
public class GraphicPanel extends javax.swing.JPanel implements ActionListener {

    private JButton b;
    private JLabel lr;
    private JLabel lg;
    private JLabel lb;
    
    /**
     * Creates new form GraphicPanel
     */
    public GraphicPanel() {
        initComponents();
        setBackground(Color.white);
        setLayout(new FlowLayout());
        b = new JButton("Choose Color");
        b.addActionListener(this);
        add(b);
        lr = new JLabel("R");
        lg = new JLabel("G");
        lb = new JLabel("B");
        add(lr);
        add(lg);
        add(lb);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.red);
        g.drawRect(12, 25, 100, 20);
        g.setColor(Color.blue);
        g.fillRect(12, 50, 100, 20);
        g.drawString("Hello World!", 12, 100);
        g.setColor(Color.black);
        g.drawRoundRect(12, 120, 50, 50, 10, 10);
        g.fillRoundRect(12, 200, 50, 50, 30, 30);
        g.drawOval(100, 10, 40, 60);
        g.drawLine(100, 70, 150, 100);
        g.drawArc(100, 150, 50, 50, 370, -270);
        g.fillArc(100, 220, 50, 50, 370, -270);
        
        Polygon p = new Polygon();
        Random r = new Random();
        for (int i = 0; i < 50; i++) {
            p.addPoint(200 + r.nextInt(100), 100 + r.nextInt(100));
        }
        
        g.drawPolygon(p);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Color c = Color.yellow;
        c = JColorChooser.showDialog(this, ":)", c);
        if (c != null) {
            b.setBackground(c);
            lr.setOpaque(true);
            lg.setOpaque(true);
            lb.setOpaque(true);
            lr.setBackground(new Color(c.getRed(), c.getRed(), c.getRed()));
            lg.setBackground(new Color(c.getGreen(), c.getGreen(), c.getGreen()));
            lb.setBackground(new Color(c.getBlue(), c.getBlue(), c.getBlue()));
        }
    }
}
