/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Soroush
 */
public class HarEsmi extends javax.swing.JDialog implements ActionListener {

    private ArrayList<String> fields;
    private ArrayList<String> values;
    private ArrayList<JPanel> panels;
    private ArrayList<JLabel> labels;
    private ArrayList<JTextField> textFields;
    private JButton submitButton;
    
    /**
     * Creates new form HarEsmi
     */
    public HarEsmi(java.awt.Frame parent, ArrayList<String> fields) {
        super(parent, true);
        initComponents();
        this.fields = fields;
        panels = new ArrayList<>();
        labels = new ArrayList<>();
        textFields = new ArrayList<>();
        submitButton = new JButton("Submit");
        setLayout(new GridLayout(fields.size() * 2 + 1, 1));
        for (int i = 0; i < fields.size(); i++) {
            panels.add(new JPanel());
            labels.add(new JLabel(fields.get(i)));
            labels.get(i).setHorizontalAlignment(SwingConstants.CENTER);
            textFields.add(new JTextField());
            panels.get(i).setLayout(new GridLayout(1, 2));
            panels.get(i).add(labels.get(i));
            panels.get(i).add(textFields.get(i));
            add(panels.get(i));
            add(new JPanel());
        }
        JPanel buttonPanel = new JPanel(new GridLayout(1, 5));
        buttonPanel.add(new JPanel());
        buttonPanel.add(new JPanel());
        buttonPanel.add(submitButton);
        buttonPanel.add(new JPanel());
        buttonPanel.add(new JPanel());
        add(buttonPanel);
        submitButton.addActionListener(this);
        values = new ArrayList<>();
        setSize(400, (fields.size() + 1) * 60);
        setResizable(false);
    }
    
    public String getValue(String key) {
        for (int i = 0; i < values.size(); i++) {
            if (fields.get(i) == key) {
                return values.get(i);
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for (int i = 0; i < fields.size(); i++) {
            values.add(textFields.get(i).getText());
        }
        setVisible(false);
    }
}
