/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Soroush
 */
public class PanelFrame extends javax.swing.JFrame {

    JPanel p1;
    JPanel p2;
    JPanel p3;
    JPanel p4;
    
    /**
     * Creates new form PanelFrame
     */
    public PanelFrame() {
        
        initComponents();
        
        setLayout(new GridLayout(1, 3));
        
        p1 = new JPanel();
        //p1.setBackground(Color.red);
        p2 = new JPanel();
        //p2.setBackground(Color.green);
        p3 = new JPanel();
        //p3.setBackground(Color.blue);
        
        add(p1);
        add(p2);
        add(p3);
        
        p2.setLayout(new GridLayout(2, 1));
        p2.add(new JButton("B11"));
        p2.add(new JButton("B12"));
        
        p1.setLayout(new BorderLayout());
        p1.add(new JButton("B13"), BorderLayout.NORTH);
        p1.add(new JButton("B14"), BorderLayout.WEST);
        p1.add(new JButton("B15"), BorderLayout.EAST);
        p1.add(new JButton("B16"), BorderLayout.SOUTH);
        
        p3.setLayout(new GridLayout(4, 2));
        p3.add(new JButton("B1"));
        p3.add(new JButton("B2"));
        p3.add(new JButton("B3"));
        p3.add(new JButton("B4"));
        p3.add(new JButton("B5"));
        
        p4 = new JPanel();
        //p4.setBackground(Color.yellow);
        p3.add(p4);
        p3.add(new JButton("B9"));
        p3.add(new JButton("B10"));
        
        p4.setLayout(new GridLayout(1, 3));
        p4.add(new JButton("B6"));
        p4.add(new JButton("B7"));
        p4.add(new JButton("B8"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
