/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.GeneralPath;

/**
 *
 * @author Soroush
 */
public class GraphicsPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraphicsPanel
     */
    public GraphicsPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g1) {
        Graphics2D g = (Graphics2D)g1;
        /*
        Point[] points = new Point[4];
        points[0] = new Point(45, 50);
        points[1] = new Point(35, 100);
        points[2] = new Point(30, 50);
        points[3] = new Point(10, 40);
        GeneralPath path = new GeneralPath();
        path.moveTo(30, 30);
        for (Point p: points) {
            path.lineTo(p.x, p.y);
        }
        path.closePath();
        g.setPaint(new GradientPaint(20, 0, Color.red, 0, 10, Color.yellow, true));
        //g.fill(path);
        g.draw(path);
        */
        g.setPaint(new GradientPaint(20, 0, Color.red, 0, 10, Color.yellow, true));
        Person person = new Person(10, 10, 30, g.getPaint(), g.getPaint());
        person.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
